# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-12-21 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171221_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(choices=[(b'linux', b'linux'), (b'mopdouban@163.com', b'mopdouban@163.com')], default='', max_length=30),
        ),
    ]
