# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-12-25 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20171225_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='\u76ee\u5f55'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', '\u8349\u7a3f'), ('published', '\u53d1\u5e03')], default='draft', max_length=10, verbose_name='\u72b6\u6001'),
        ),
    ]
