# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-12-10 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20171206_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(choices=[(b'linux', b'linux'), (b'yan939', b'yan939'), (b'biubiu', b'biubiu')], default='', max_length=30),
        ),
    ]
