# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-12-06 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import simditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=simditor.fields.RichTextField(verbose_name='\u5185\u5bb9'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='title', max_length=70, verbose_name='\u6807\u9898'),
        ),
    ]
