# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-11-25 13:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171125_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleauthor',
            name='author',
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.DeleteModel(
            name='ArticleAuthor',
        ),
    ]
