# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-12-04 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='about/%Y/%m/%d'),
        ),
    ]
